import {CommonModule} from '@angular/common'; import {Component,inject,OnInit,signal} from '@angular/core'; import {FormsModule} from '@angular/forms'; import {RouterLink} from '@angular/router'; import {forkJoin} from 'rxjs';
import {AuthService} from '../../../../core/config/auth/services/auth.service'; import {ClassGroup} from '../../../school/class-groups/models/class-group.model'; import {ClassGroupService} from '../../../school/class-groups/services/class-group.service'; import {TimeSlot} from '../../../school/time-slots/models/time-slot.model'; import {TimeSlotService} from '../../../school/time-slots/services/time-slot.service'; import {ExpectedStudentAttendance,StudentAttendanceStatus} from '../../models/student-attendance.model'; import {StudentAttendanceService} from '../../services/student-attendance.service';
interface Row extends ExpectedStudentAttendance{editStatus:StudentAttendanceStatus;editLateMinutes:number|null;editReason:string;editJustified:boolean;editNotes:string;}
@Component({selector:'app-student-attendance',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./student-attendance.component.html',styleUrl:'./student-attendance.component.scss'})
export class StudentAttendanceComponent implements OnInit{private api=inject(StudentAttendanceService);private classApi=inject(ClassGroupService);private slotApi=inject(TimeSlotService);readonly auth=inject(AuthService);classes=signal<ClassGroup[]>([]);slots=signal<TimeSlot[]>([]);rows=signal<Row[]>([]);loading=signal(false);saving=signal(false);message=signal('');error=signal('');selectedDate=this.today();classGroupId:number|null=null;timeSlotId:number|null=null;
 ngOnInit(){forkJoin({classes:this.classApi.getAll(),slots:this.slotApi.getAll()}).subscribe({next:r=>{this.classes.set(r.classes.filter(x=>x.status==='ACTIVE'));this.slots.set(r.slots.filter(x=>x.active).sort((a,b)=>a.displayOrder-b.displayOrder));this.classGroupId=this.classes()[0]?.id??null;this.timeSlotId=this.slots()[0]?.id??null;if(this.classGroupId&&this.timeSlotId)this.load();},error:e=>this.error.set(this.err(e))});}
 load(){this.message.set('');this.error.set('');if(!this.classGroupId||!this.timeSlotId){this.rows.set([]);return;}this.loading.set(true);this.api.expected(this.selectedDate,this.classGroupId,this.timeSlotId).subscribe({next:x=>{this.rows.set(x.map(v=>({...v,editStatus:v.status??'PRESENT',editLateMinutes:v.lateMinutes??0,editReason:v.reason??'',editJustified:v.justified??false,editNotes:v.notes??''})));this.loading.set(false);},error:e=>{this.rows.set([]);this.loading.set(false);this.error.set(this.err(e));}});}
 setStatus(r:Row,s:StudentAttendanceStatus){r.editStatus=s;if(s!=='RETARD')r.editLateMinutes=0;if(s==='PRESENT'){r.editReason='';r.editJustified=false;}}
 count(s:StudentAttendanceStatus){return this.rows().filter(x=>x.editStatus===s).length;}
 save(){this.error.set('');this.message.set('');const rows=this.rows();if(!rows.length)return;const late=rows.find(x=>x.editStatus==='RETARD'&&(!x.editLateMinutes||x.editLateMinutes<=0));if(late){this.error.set(`Indiquez le nombre de minutes de retard pour ${late.studentName}.`);return;}const scheduleEntryId=rows[0].scheduleEntryId;if(rows.some(x=>x.scheduleEntryId!==scheduleEntryId)){this.error.set('Plusieurs cours ont été détectés pour ce créneau. Vérifiez l’emploi du temps.');return;}this.saving.set(true);this.api.saveBatch({scheduleEntryId,date:this.selectedDate,attendances:rows.map(x=>({studentId:x.studentId,status:x.editStatus,lateMinutes:x.editStatus==='RETARD'?x.editLateMinutes:0,reason:x.editReason.trim()||null,justified:x.editStatus==='ABSENT'?x.editJustified:false,notes:x.editNotes.trim()||null}))}).subscribe({next:()=>{this.saving.set(false);this.message.set('Assiduité des élèves enregistrée. Les parents sont automatiquement informés en cas d’absence ou de retard.');this.load();},error:e=>{this.saving.set(false);this.error.set(this.err(e));}});}
 private today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}private err(e:any){return e?.error?.message??e?.error?.detail??e?.message??'Une erreur est survenue.';}}
