import { CommonModule } from '@angular/common';import { Component,OnInit,inject,signal } from '@angular/core';import { FormsModule } from '@angular/forms';import { ActivatedRoute,RouterLink } from '@angular/router';import { forkJoin } from 'rxjs';import { HrService } from '../../services/hr.service';import { CompensationPlan,SubjectReference,Teacher,TeacherRate,TeacherStatus,TeachingAssignment } from '../../models/hr.model';import { SchoolYearService } from '../../../school/school-years/services/school-year.service';import { ClassGroupService } from '../../../school/class-groups/services/class-group.service';import { SchoolYear } from '../../../school/school-years/models/school-year.model';import { ClassGroup } from '../../../school/class-groups/models/class-group.model';
@Component({selector:'app-teacher-detail',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./teacher-detail.component.html',styleUrl:'./teacher-detail.component.scss'})
export class TeacherDetailComponent implements OnInit{private route=inject(ActivatedRoute);private api=inject(HrService);private yearsApi=inject(SchoolYearService);private classesApi=inject(ClassGroupService);id=Number(this.route.snapshot.paramMap.get('id'));teacher=signal<Teacher|null>(null);subjects=signal<SubjectReference[]>([]);assignments=signal<TeachingAssignment[]>([]);plans=signal<CompensationPlan[]>([]);rates=signal<TeacherRate[]>([]);years=signal<SchoolYear[]>([]);classes=signal<ClassGroup[]>([]);error=signal('');success=signal('');tab='subjects';subjectId:number|null=null;assign={schoolYearId:null as number|null,subjectId:null as number|null,classGroupId:null as number|null,startDate:new Date().toISOString().slice(0,10),endDate:null as string|null};plan:any={compensationType:'MONTHLY',schoolYearId:null,monthlySalary:null,hourlyRate:null,fixedPart:null,expectedMonthlyHours:null,effectiveFrom:new Date().toISOString().slice(0,10),effectiveUntil:null};rate:any={schoolYearId:null,classGroupId:null,subjectId:null,workType:'COURSE',hourlyRate:null,effectiveFrom:new Date().toISOString().slice(0,10),effectiveUntil:null};endTarget:TeachingAssignment|null=null;endDate=new Date().toISOString().slice(0,10);
 ngOnInit(){forkJoin({s:this.api.subjects(),y:this.yearsApi.getAll(),c:this.classesApi.getAll()}).subscribe(r=>{this.subjects.set(r.s);this.years.set(r.y);this.classes.set(r.c);const y=r.y.find(x=>x.currentYear);this.assign.schoolYearId=y?.id??null;this.plan.schoolYearId=y?.id??null;this.rate.schoolYearId=y?.id??null});this.load()}
 load(){forkJoin({t:this.api.teacher(this.id),a:this.api.assignmentsByTeacher(this.id)}).subscribe({next:r=>{this.teacher.set(r.t);this.assignments.set(r.a);this.api.plans(r.t.employeeId).subscribe(v=>this.plans.set(v));this.api.rates(this.id).subscribe(v=>this.rates.set(v))},error:e=>this.error.set(this.msg(e))})}
 availableSubjects(){const ids=new Set(this.teacher()?.subjects.map(s=>s.id)??[]);return this.subjects().filter(s=>!ids.has(s.id))}
 addSubject(){if(!this.subjectId)return;this.api.addSubject(this.id,this.subjectId).subscribe({next:()=>{this.subjectId=null;this.success.set('Matière ajoutée.');this.load()},error:e=>this.error.set(this.msg(e))})}
 removeSubject(s:SubjectReference){this.api.removeSubject(this.id,s.id).subscribe({next:()=>this.load(),error:e=>this.error.set(this.msg(e))})}
 status(s:TeacherStatus){this.api.changeTeacherStatus(this.id,s).subscribe({next:t=>this.teacher.set(t),error:e=>this.error.set(this.msg(e))})}
 createAssignment(){if(!this.assign.schoolYearId||!this.assign.subjectId||!this.assign.classGroupId)return;this.api.createAssignment({teacherId:this.id,schoolYearId:this.assign.schoolYearId,subjectId:this.assign.subjectId,classGroupId:this.assign.classGroupId,startDate:this.assign.startDate,endDate:this.assign.endDate}).subscribe({next:()=>{this.success.set('Affectation créée.');this.load()},error:e=>this.error.set(this.msg(e))})}
 askEnd(a:TeachingAssignment){this.endTarget=a;this.endDate=new Date().toISOString().slice(0,10)} confirmEnd(){if(!this.endTarget||!this.endDate)return;this.api.endAssignment(this.endTarget.id,this.endDate).subscribe({next:()=>{this.endTarget=null;this.success.set('Affectation clôturée.');this.load()},error:e=>this.error.set(this.msg(e))})}
 createPlan(){const t=this.teacher();if(!t)return;this.api.createPlan({...this.plan,employeeId:t.employeeId}).subscribe({next:()=>{this.success.set('Plan de rémunération créé.');this.load()},error:e=>this.error.set(this.msg(e))})}
 createRate(){if(!this.rate.schoolYearId||!this.rate.hourlyRate)return;this.api.createRate({...this.rate,teacherId:this.id}).subscribe({next:()=>{this.success.set('Tarif horaire créé.');this.load()},error:e=>this.error.set(this.msg(e))})}
 money(v:number|null){return v==null?'—':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'DZD',maximumFractionDigits:0}).format(v)} private msg(e:any){return e?.error?.message||e?.error?.detail||'Une erreur est survenue.'}
}
